Rename UMBREL_ROOT to NODE_ROOT, disable backups for now

diff --git a/scripts/backup/backup b/scripts/backup/backup
--- a/scripts/backup/backup
+++ b/scripts/backup/backup
@@ -2,12 +2,12 @@
 
 set -euo pipefail
 
-UMBREL_ROOT="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/../..)"
-BACKUP_ROOT="${UMBREL_ROOT}/.backup/$RANDOM"
+NODE_ROOT="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/../..)"
+BACKUP_ROOT="${NODE_ROOT}/.backup/$RANDOM"
 BACKUP_FOLDER_NAME="backup"
 BACKUP_FOLDER_PATH="${BACKUP_ROOT}/${BACKUP_FOLDER_NAME}"
 BACKUP_FILE="${BACKUP_ROOT}/backup.tar.gz.pgp"
-BACKUP_STATUS_FILE="${UMBREL_ROOT}/statuses/backup-status.json"
+BACKUP_STATUS_FILE="${NODE_ROOT}/statuses/backup-status.json"
 
 check_dependencies () {
   for cmd in "$@"; do
@@ -23,7 +23,7 @@ check_dependencies openssl tar gpg shuf curl
 # Deterministically derives 128 bits of cryptographically secure entropy
 derive_entropy () {
   identifier="${1}"
-  umbrel_seed=$(cat "${UMBREL_ROOT}/db/umbrel-seed/seed") || true
+  umbrel_seed=$(cat "${NODE_ROOT}/db/umbrel-seed/seed") || true
 
   if [[ -z "$umbrel_seed" ]] || [[ -z "$identifier" ]]; then
     >&2 echo "Missing derivation parameter, this is unsafe, exiting."
@@ -34,7 +34,7 @@ derive_entropy () {
   printf "%s" "${identifier}" | openssl dgst -sha256 -hmac "${umbrel_seed}" | sed 's/^.* //'
 }
 
-[[ -f "${UMBREL_ROOT}/.env" ]] && source "${UMBREL_ROOT}/.env"
+[[ -f "${NODE_ROOT}/.env" ]] && source "${NODE_ROOT}/.env"
 BITCOIN_NETWORK=${BITCOIN_NETWORK:-mainnet}
 
 echo "Deriving keys..."
@@ -44,20 +44,20 @@ encryption_key=$(derive_entropy "umbrel_backup_encryption_key")
 
 echo "Creating backup..."
 
-if [[ ! -f "${UMBREL_ROOT}/lnd/data/chain/bitcoin/${BITCOIN_NETWORK}/channel.backup" ]]; then
+if [[ ! -f "${NODE_ROOT}/lnd/data/chain/bitcoin/${BITCOIN_NETWORK}/channel.backup" ]]; then
     echo "No channel.backup file found, skipping backup..."
     exit 1
 fi
 
 mkdir -p "${BACKUP_FOLDER_PATH}"
 
-cp --archive "${UMBREL_ROOT}/lnd/data/chain/bitcoin/${BITCOIN_NETWORK}/channel.backup" "${BACKUP_FOLDER_PATH}/channel.backup"
+cp --archive "${NODE_ROOT}/lnd/data/chain/bitcoin/${BITCOIN_NETWORK}/channel.backup" "${BACKUP_FOLDER_PATH}/channel.backup"
 
 # We want to back up user settings too, however we currently store the encrypted
 # mnemonic in this file which is not safe to backup remotely.
 # Uncomment this in the future once we've ensured there's no critical data in
 # this file.
-# cp --archive "${UMBREL_ROOT}/db/user.json" "${BACKUP_FOLDER_PATH}/user.json"
+# cp --archive "${NODE_ROOT}/db/user.json" "${BACKUP_FOLDER_PATH}/user.json"
 
 echo "Adding random padding..."
 
@@ -94,28 +94,28 @@ tar \
 #   --verbose \
 #   --gzip
 
-BACKUP_API_URL="https://pvf3ozmmfl.execute-api.us-east-1.amazonaws.com/prod/v1/upload"
+#BACKUP_API_URL="https://pvf3ozmmfl.execute-api.us-east-1.amazonaws.com/prod/v1/upload"
 
 if [[ $BITCOIN_NETWORK == "testnet" ]]; then
-    BACKUP_API_URL="https://as0ot0lg7h.execute-api.us-east-1.amazonaws.com/dev/v1/upload"
+    #BACKUP_API_URL="https://as0ot0lg7h.execute-api.us-east-1.amazonaws.com/dev/v1/upload"
 fi
 if [[ $BITCOIN_NETWORK == "regtest" ]]; then
-    BACKUP_API_URL="https://5fxwqbum7g.execute-api.us-east-1.amazonaws.com/dev/v1/upload"
+    #BACKUP_API_URL="https://5fxwqbum7g.execute-api.us-east-1.amazonaws.com/dev/v1/upload"
 fi
 
 echo "Uploading backup..."
-if curl --socks5 localhost:9150 -F "file=@/${BACKUP_FILE}" "${BACKUP_API_URL}/${backup_id}"; then
-  status="success"
+#if curl --socks5 localhost:9150 -F "file=@/${BACKUP_FILE}" "${BACKUP_API_URL}/${backup_id}"; then
+#  status="success"
 else
-  status="failed"
-fi
-echo
+#  status="failed"
+#fi
+#echo
 
 rm -rf "${BACKUP_ROOT}"
 
 # Update status file
 cat <<EOF > ${BACKUP_STATUS_FILE}
-{"status": "${status}", "timestamp": $(date +%s000)}
+{"status": "success", "timestamp": $(date +%s000)}
 EOF
 
 echo "============================="
