Remove more Umbrel references, set neutrino feeurl for mainnet

diff --git a/scripts/umbrel-os/external-storage/update-from-sdcard b/scripts/umbrel-os/external-storage/update-from-sdcard
--- a/scripts/umbrel-os/external-storage/update-from-sdcard
+++ b/scripts/umbrel-os/external-storage/update-from-sdcard
@@ -31,13 +31,18 @@ check_semver_range () {
 main () {
   check_root
   check_dependencies jq
-  echo "Checking if SD card Umbrel is newer than external storage..."
+  echo "Checking if SD card Citadel is newer than external storage..."
   local external_version=$(cat "${NODE_ROOT}/info.json" | jq -r .version | cut -d "-" -f "1")
   local sd_version=$(cat "${SD_NODE_ROOT}/info.json" | jq -r .version | cut -d "-" -f "1")
 
   if ! check_semver_range ">${external_version}" "${sd_version}"; then
-    echo "No, SD version is not newer, exiting."
-    exit 0
+    echo "No, SD version is not newer."
+    # If external installation contains a .citadel file exit, otherwise continue
+    if [[ -f "${NODE_ROOT}/.citadel" ]]; then
+      echo "External installation is a Citadel which doesn't need an update."
+      exit 0
+    fi
+    echo "Detected an Umbrel installation on exteral storage, upgrading it to Citadel..."
   fi
 
   echo "Yes, SD version is newer."
@@ -45,13 +50,16 @@ main () {
   # e.g `1.2.3-beta <2.0.0` will become `1.2.3` due to striping the `-`
   local update_requirement=$(cat "${SD_NODE_ROOT}/info.json" | jq -r .requires | cut -d "-" -f "1")
 
-  echo "Checking if the external storage version \"${external_version}\" satisfies update requirement \"${update_requirement}\"..."
-  if ! check_semver_range "${update_requirement}" "${external_version}"; then
-    echo "No, we can't do an automatic update, exiting."
-    exit 0
+  # Only do this check ${NODE_ROOT}/.citadel doesn't exist
+  if [[ -f "${NODE_ROOT}/.citadel" ]]; then
+    echo "Checking if the external storage version \"${external_version}\" satisfies update requirement \"${update_requirement}\"..."
+    if ! check_semver_range "${update_requirement}" "${external_version}"; then
+      echo "No, we can't do an automatic update, exiting."
+      exit 0
+    fi
+    echo "Yes, it does, attempting an automatic update..."
   fi
-
-  echo "Yes, it does, attempting an automatic update..."
+  
   "${NODE_ROOT}/scripts/update/update" --path "${SD_NODE_ROOT}"
 }
 
